# Do you want to keep requiring the user to run the /bmdiscover command to discover the map?
# Or do you want the BlueMap to be automatically discovered when someone creates a new map?
AutomaticMapDiscovery: false
